openapi: 3.0.3
info:
  title: Your Project API
  version: 1.0.0
  description: Your project description
paths:
  /code/:
    post:
      operationId: code_create
      description: Authentication or registration and authorization after entered
        code.
      tags:
      - code
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /phone/:
    post:
      operationId: phone_create
      description: |-
        Enter phone number. Format +11234567890.
        After follow page /code/
      tags:
      - phone
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /profile/:
    get:
      operationId: profile_retrieve
      description: Profile CustomUser
      tags:
      - profile
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
    put:
      operationId: profile_update
      description: Profile CustomUser
      tags:
      - profile
      security:
      - jwtAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /token/refresh/:
    post:
      operationId: token_refresh_create
      description: |-
        Takes a refresh type JSON web token and returns an access type JSON web
        token if the refresh token is valid.
      tags:
      - token
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/TokenRefresh'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TokenRefresh'
          description: ''
components:
  schemas:
    TokenRefresh:
      type: object
      properties:
        access:
          type: string
          readOnly: true
        refresh:
          type: string
          writeOnly: true
      required:
      - access
      - refresh
  securitySchemes:
    jwtAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
